name: DBSSync2
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libsodium=1.0.20
  - libsqlite=3.46.1
  - libxml2=2.12.7
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - mkl=2024.1.0
  - nest-asyncio=1.6.0
  - numpy=2.1.2
  - openssl=3.3.2
  - packaging=24.1
  - pandas=2.2.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.9
  - python-tzdata=2024.2
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=26.2.0
  - setuptools=75.1.0
  - six=1.16.0
  - stack_data=0.6.2
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - pip:
      - altgraph==0.17.4
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.54.1
      - h5py==3.12.1
      - idna==3.10
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mne==1.8.0
      - pefile==2023.2.7
      - pillow==11.0.0
      - pooch==1.8.2
      - pyinstaller==6.11.0
      - pyinstaller-hooks-contrib==2024.9
      - pymatreader==1.0.0
      - pyparsing==3.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.15.0
      - python-dateutil==2.9.0.post0
      - pywin32-ctypes==0.2.3
      - pyxdf==1.16.8
      - requests==2.32.3
      - scipy==1.14.1
      - tqdm==4.66.5
      - urllib3==2.2.3
      - xmltodict==0.14.2
prefix: C:\Users\Juliette\anaconda3\envs\resync_test_env
